version: '3.8'

services:

  mongo:
    image: mongo
    container_name: "database-db"
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - E:\Device File\OneDrive\Desktop\data\mongo-node-app-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  node-demo-app:
    image: gyarsilalsolanki011/node-demo-app
    container_name: "node-demo-app"
    ports:
      - "3000:3000"
    links:
      - mongo
   